# Generated by Django 4.2.4 on 2024-06-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='address',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donor',
            name='mobileNo',
            field=models.IntegerField(),
        ),
    ]
