# Generated by Django 4.2.4 on 2024-06-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='any_blood_related_disease',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='mobileNo',
            field=models.IntegerField(),
        ),
    ]
