# Generated by Django 4.2.4 on 2024-06-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_donor_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='complete_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='confirm_password',
            field=models.CharField(default='0000', max_length=50),
        ),
        migrations.AddField(
            model_name='donor',
            name='password',
            field=models.CharField(default='0000', max_length=50),
        ),
    ]
