# Generated by Django 4.2.4 on 2024-06-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_seeker_alter_donor_gender_alter_donor_bloodgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='0000', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='login_Seeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='0000', max_length=50)),
            ],
        ),
    ]
