# Generated by Django 4.2.4 on 2024-06-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_donor_address_alter_donor_mobileno'),
        ('api', '0007_contact_us'),
    ]

    operations = [
    ]
