# Generated by Django 5.0 on 2024-06-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='emailId',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
