# Generated by Django 5.0 on 2024-06-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_donor_emailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='emailId',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
