# Generated by Django 5.0 on 2024-07-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_donor_lat_donor_lng_seeker_lat_seeker_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSubscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField()),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
            ],
        ),
    ]
