# Generated by Django 5.0 on 2024-07-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_notificationsubscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsubscriptions',
            name='UserEmail',
            field=models.TextField(default='UserNameNotFound'),
        ),
    ]
