# Generated by Django 5.0 on 2024-07-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userdevice_delete_notificationsubscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='user',
            field=models.CharField(default='User not found', max_length=200, unique=True),
        ),
    ]
