# Generated by Django 5.0 on 2024-07-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_broadcastmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='broadcastList',
            field=models.ManyToManyField(to='api.broadcastmodel'),
        ),
    ]
