# Generated by Django 5.0 on 2024-07-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_seeker_broadcastlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_Donor',
        ),
        migrations.DeleteModel(
            name='login_Seeker',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='confirm_password',
        ),
        migrations.AddField(
            model_name='donor',
            name='type',
            field=models.CharField(default='Donor', max_length=50),
        ),
        migrations.AddField(
            model_name='seeker',
            name='type',
            field=models.CharField(default='Donor', max_length=50),
        ),
        migrations.AlterField(
            model_name='donor',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
