# Generated by Django 5.0 on 2024-07-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_broadcastmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('logo', models.ImageField(null=True, upload_to='notification_logos/')),
                ('url', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Chat', 'Chat'), ('Broadcast', 'Broadcast'), ('Map', 'Map'), ('BloodCamp', 'BloodCamp'), ('', '')], max_length=10)),
            ],
        ),
    ]
