# Generated by Django 5.0 on 2024-07-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='user',
            field=models.CharField(default='User not found', max_length=100, unique=True),
        ),
    ]
