# Generated by Django 5.0 on 2024-07-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_userdevice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='type',
            field=models.CharField(default='DONOR', max_length=50),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='type',
            field=models.CharField(default='SEEKER', max_length=50),
        ),
    ]
