# Generated by Django 5.0 on 2024-07-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_donor_type_alter_seeker_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='notificaitons',
            field=models.ManyToManyField(to='api.notifications'),
        ),
        migrations.AddField(
            model_name='seeker',
            name='notificaitons',
            field=models.ManyToManyField(to='api.notifications'),
        ),
    ]
