# Generated by Django 5.0 on 2024-07-31 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_donor_notificaitons_seeker_notificaitons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='url',
            new_name='page_url',
        ),
    ]
