# Generated by Django 5.0 on 2024-07-31 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_notificaitons_donor_notifications_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='created_at',
            new_name='date',
        ),
    ]
