# Generated by Django 5.0 on 2024-07-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_chatbase_message_donor_chatbases_chatbase_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='ChatBases',
            field=models.ManyToManyField(to='api.chatbase'),
        ),
    ]
