# Generated by Django 5.0 on 2024-07-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_donor_chatbases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='ChatBases',
            field=models.ManyToManyField(related_name='donors', to='api.chatbase'),
        ),
    ]
