# Generated by Django 5.0 on 2024-07-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_donor_chatbases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbase',
            name='messages',
            field=models.ManyToManyField(related_name='chat_bases', to='api.message'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='notifications',
            field=models.ManyToManyField(related_name='donors', to='api.notifications'),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='ChatBases',
            field=models.ManyToManyField(related_name='Seeker', to='api.chatbase'),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='broadcastList',
            field=models.ManyToManyField(related_name='Seeker', to='api.broadcastmodel'),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='notifications',
            field=models.ManyToManyField(related_name='Seeker', to='api.notifications'),
        ),
    ]
