# Generated by Django 5.0 on 2024-07-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_chatbase_messages_alter_donor_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='dp',
            field=models.ImageField(default='default_pics/blooddonor.png', upload_to='dp_images/'),
        ),
        migrations.AddField(
            model_name='seeker',
            name='dp',
            field=models.ImageField(default='default_pics/job-seeker.png', upload_to='dp_images/'),
        ),
    ]
