# Generated by Django 5.0 on 2024-08-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_donor_blooddonated_donor_eligible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='ChatBases',
            field=models.ManyToManyField(blank=True, related_name='Seeker', to='api.chatbase'),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='broadcastList',
            field=models.ManyToManyField(blank=True, related_name='Seeker', to='api.broadcastmodel'),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='Seeker', to='api.notifications'),
        ),
    ]
