# Generated by Django 5.0 on 2024-08-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_slider_captitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='capTitle',
        ),
        migrations.AddField(
            model_name='seeker',
            name='bloodSeeked',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
