# Generated by Django 5.0 on 2024-08-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_broadcastmodel_donated_broadcastmodel_donor_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='totalBloodDonated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
