# Generated by Django 5.0 on 2024-08-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_donor_totalblooddonated'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmodel',
            name='notified_donors',
            field=models.ManyToManyField(related_name='Broadcastmodel', to='api.donor'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='ChatBases',
            field=models.ManyToManyField(blank=True, related_name='donors', to='api.chatbase'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='donors', to='api.notifications'),
        ),
    ]
