# Generated by Django 5.0 on 2024-08-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_broadcastmodel_notified_donors_alter_donor_chatbases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Deny', 'Deny')], default='Pending', max_length=10),
        ),
    ]
