# Generated by Django 5.0 on 2024-08-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_notifications_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='broadcastId',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Ignore', 'Ignore'), ('Deny', 'Deny')], default='Pending', max_length=10),
        ),
    ]
