# Generated by Django 5.0 on 2024-08-04 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_broadcastmodel_accepted_donors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastmodel',
            name='donor_assign',
        ),
    ]
