# Generated by Django 5.0 on 2024-08-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_broadcastmodel_donor_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('saved', 'saved'), ('read', 'read')], default='saved', max_length=15),
        ),
    ]
