# Generated by Django 5.0 on 2024-08-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='uId',
            field=models.CharField(default='DO', max_length=50),
        ),
        migrations.AddField(
            model_name='seeker',
            name='uId',
            field=models.CharField(default='SE', max_length=50),
        ),
    ]
