# Generated by Django 5.0 on 2024-08-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_donor_uid_seeker_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='bloodDonated',
            field=models.ManyToManyField(blank=True, related_name='donors', to='api.broadcastmodel'),
        ),
    ]
