# Generated by Django 5.0 on 2024-08-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_donor_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbase',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='chat_bases', to='api.message'),
        ),
    ]
