# Generated by Django 5.0 on 2024-08-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_chatbase_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbase',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
