# Generated by Django 4.2.4 on 2024-08-06 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_bloodbank_blooddrive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodbank',
            old_name='name',
            new_name='bank_name',
        ),
    ]
