# Generated by Django 4.2.4 on 2024-08-06 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_rename_name_bloodbank_bank_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodbank',
            old_name='bank_name',
            new_name='name',
        ),
    ]
